### PR TITLE
Feature/connect4

### PR DESCRIPTION
**Pull request by juliansweatt**
# Feature: Connect 4 Game
## Description
Connect 4 implementation for the Plethora API/UI using PyGame. This version of Connect 4 works with two human players, red and green. Games can be repeated and score is kept.

## Documentation
Further documentation is included in the source-code, written as PyDoc docstrings.

## Future Improvements
Once PlethoraAPI supports user management, player names and color preferences could be passed in. The game could also return a score for PlethoraAPI to manage a leaderboard.

## Review
Please review this pull request and recommend any changes you see fit. Please do not complete the merge yourself, I would like to do a squash first.

### CODE REVIEW

**Comment by dylnmc** [comment]
@juliansweatt this looks great!

Coloring the columns based on the user's turn is a very nice feature, and you've integrated it really well with plethoraAPI.

One thing I am curious about is that you call `self.resetWindow()` in `self.exitGame()`, and I was wondering if that was to allow the game to work when it is started again after exiting to the main UI. If that is the case, then either developers can use something like you used, or maybe we can call `__init__()` again or somehow restart the game. I am not quite sure, but I think that an `onstart()` function called from the API could be useful so that instead of initializing things in `__init__()` you'd initialize them in `onstart()`. Or maybe we should destroy the game instance and re-invoke it each time a game is loaded. Not sure; what do you think?

Another thing I saw was invoking `pygame.mouse.get_pressed()[0]` in `onevent(self, event)`. The `event` in that function is a pygame event, so it has `button` attribute, which you can check instead of invoking `pygame.mouse.get_pressed()`. See https://github.com/juliansweatt/mini-games/blob/eff36e7dba5547c44c74e73a5a2c42132c317df3/src/arcade/games/testgame/testgame.py#L68

Everything else is awesome. Good job with doc strings, comments, integrating with API, etc.

**Comment by juliansweatt** [comment]
@dylnmc 
Thanks for the input!

**On Start**
I originally set up all the dimensions for a regular Pygame game. To convert it over for Plethora, I used an expand window function which manipulates some global variables. However, when exiting to the plethora menu and opening the game again, this expand function would be re-called, making the game far too big, so I made the `self.resetWindow()` function to shrink the new instance back down every time the user goes back to the menu. This could likely be fixed by using an instance of a config class or something like that instead of global variables, so I think either the `__init__()` or the `onstart()` would both work. Currently the game gets reinstantiated on every launch, but the global variables are persistent.

**Mouse Buttons**
Thank you for pointing that out. I didn't realize the button information was passed from the event. Fixed the mouse button in the most [Recent Commit](https://github.com/juliansweatt/mini-games/pull/1/commits/f0fac961ec2217935cb4f6f7bf3735b95cd30313).

**Comment by juliansweatt** [comment]
@dylnmc Quick follow-up on the global variables/game init topic.

I noticed the problem in connect-4, so as I'm starting Bomberman I've chosen to keep my dimensions and setup variables in a [`GameConfig()`](https://github.com/juliansweatt/mini-games/blob/c50c4e90923f7a5ec3dc8e64c2d2c2d7cf33957c/src/arcade/games/bomberman/bomberman.py#L15) class so that it will be forced to reinitialize any time the game is relaunched, to avoid past games influencing the global variables of new games.

**Comment by juliansweatt** [comment]
# Squashed & Merged to Develop
**Review Time:** 1 Week

**Pull request merged**
